name: F1 CICD

on:
  push:
    branches: [ "f1" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Deploy to AWS Lightsail
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          port: 22
          script: | 
            cd ~/app
            git pull origin main
            # Nếu chạy docker-compose
            # docker-compose down
            # docker-compose up -d --build
            # Hoặc restart systemd service
            # sudo systemctl restart myapp