name: F1 CICD

on:
  push:
    branches: [ "f1" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Deploy to AWS Lightsail
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          port: 22
          script: | 
            cd ~/app
            git fetch origin f1
            git checkout f1 || git checkout -b f1 origin/f1
            git pull origin f1

            # build / restart service ở đây
            npm install --production
            pm2 restart myapp || pm2 start index.js --name myapp